#cloud-config
---
write_files:
  - path: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  - path: /etc/apt/sources.list.d/kubernetes-xenial.list
    content: |
      deb https://apt.kubernetes.io/ kubernetes-xenial main
  - path: /tmp/kubeadm.conf
    content: |
      ---
      apiVersion: kubeadm.k8s.io/v1beta1
      kind: InitConfiguration
      localAPIEndpoint:
        bindPort: 6443
      ---
      apiVersion: kubeadm.k8s.io/v1beta1
      kind: ClusterConfiguration
      kubernetesVersion: v1.14.0
      apiServer:
        timeoutForControlPlane: 4m0s
      certificatesDir: /etc/kubernetes/pki
      clusterName: hnetes
      controlPlaneEndpoint: ""
      dns:
        type: CoreDNS
      etcd:
        local:
          dataDir: /var/lib/etcd
      imageRepository: k8s.gcr.io
      networking:
        dnsDomain: cluster.local
        serviceSubnet: 10.96.0.0/12
runcmd:
  - apt-get install -qq apt-transport-https ca-certificates curl
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  - apt-get update -q
  - apt-get install -qq docker-ce docker-ce-cli containerd.io kubelet kubeadm kubectl
  - |
    cat > /etc/docker/daemon.json <<EOF
    {
      "exec-opts": ["native.cgroupdriver=systemd"],
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "storage-driver": "overlay2"
    }
    EOF
  - mkdir -p /etc/systemd/system/docker.service.d
  - systemctl daemon-reload
  - systemctl restart docker
  - apt-mark hold kubelet kubeadm kubectl
  - kubeadm init --config /tmp/kubeadm.conf | grep -A1 '^kubeadm join' > /root/join-command
  - while ! kubectl --kubeconfig /etc/kubernetes/admin.conf cluster-info; do echo 'Kubernetes not yet up... retrying in 5s'; sleep 5; done
  - kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
