#cloud-config
---
write_files:
  - path: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  - path: /etc/apt/sources.list.d/kubernetes-xenial.list
    content: |
      deb https://apt.kubernetes.io/ kubernetes-xenial main
runcmd:
  - apt-get install -qq apt-transport-https ca-certificates curl
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  - apt-get update -q
  - apt-get install -qq docker-ce docker-ce-cli containerd.io kubelet kubeadm kubectl
  - |
    cat > /etc/docker/daemon.json <<EOF
    {
      "exec-opts": ["native.cgroupdriver=systemd"],
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "storage-driver": "overlay2"
    }
    EOF
  - mkdir -p /etc/systemd/system/docker.service.d
  - systemctl daemon-reload
  - systemctl restart docker
  - apt-mark hold kubelet kubeadm kubectl
